# This is a basic workflow to help you get started with Actions

name: React App CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
    - main
    - releases/*
  #pull_request:
   # branches: [ main ]
env:
  owner: priyamoorthy28
  domain: github.io
  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-dev-test:
    name: Deploy to Dev test environment
    runs-on: ubuntu-latest
    environment: 
      name: DevTest
      url: https://${{ env.owner }}.${{ env.domain }}/${{ env.repo }}//
    env:
      repo: ci-cd-with-actions
    steps:
      - name: Checkout 
        uses: actions/checkout@v2.3.1
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
 
  deploy-prod:
    name: Deploy to Production environment
    needs: [deploy-dev-test]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://${{ env.owner }}.${{ env.domain }}/${{ env.repo }}//
    env:
      repo: actions-workshop-prod
    steps:
     - name: Checkout 
       uses: actions/checkout@v2.3.1
     - name: Install and Build
       run: |
         npm install
         npm run build
    - name: Deploy
     uses: JamesIves/github-pages-deploy-action@4.1.0
     with: 
       branch: gh-pages
       folder: build
       token: ${{ secrets.TOKEN }}
       repository-name: ${{ env.owner }}/${{ env.repo }}
